src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/exception/AuthCodeAlreadyVerifiedException.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/exception/InvalidAuthCodeException.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/request/VerifyAuthCodeRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/VerifyAuthCodeService.java
=> 🔀 :: (#116) 이메일 인증코드 확인 API

src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserFacade.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/request/LoginRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserLoginService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserSignupService.java
=> 🔀 :: (#124) 유저 로그인 API

src/main/java/kr/hs/entrydsm/rollsroyce/domain/status/domain/facade/StatusFacade.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserFacade.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/response/StatusResponse.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserStatusService.java
=> 🔀 :: (#129) 유저 상태 조회

src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/request/PasswordRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/ChangePasswordService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/VerifyAuthCodeService.java
=> 🔀 :: (#130) 비밀번호 변경

src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserFacade.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/request/SignupRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserLoginService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserSignupService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
=> 🔀 :: (#171) 유저 회원가입

src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/QualificationCaseRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/facade/ScoreFacade.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/presentation/ScoreController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/presentation/dto/request/UpdateGraduationRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/presentation/dto/request/UpdateQualificationRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/service/UpdateGraduationService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/service/UpdateQualificationService.java
=> 🔀 :: (#189) 검정고시 정보 입력

src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserFacade.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendAuthCodeService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserSignupService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserTokenRefreshService.java
=> 🔀 :: (#187) 유저 토큰 재발급

src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendAuthCodeService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/exception/MessageRejectedException.java
=> 🔀 :: (#218) 이메일 인증 

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/AdminController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/GetApplicantsRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantsService.java
https://tailerbox.tistory.com/30
위의 사이트에 들어가시면 
"하지만, GET 요청을 통해 전달되는 QueryString의 경우 @RequestParam 을 사용하게 되면 각각의 인자단위로 맵핑을 지정해야하며, @ModelAttribute 를 통한 객체 전달 시 상기 언급한 @JsonProperty 어노테이션을 사용하더라도 변환이 되지 않는다." 라고 합니다. 실제로도 먹히지 않았구요
그렇다고 @RequestParam를 사용하기엔 복잡해서 카멜케이스로 요청을 하고 VO로 받기로 하였습니다.
=> 🔀 :: (#318) isNotSubmitted 추가 및 카멜케이스 요청으로 변경

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/LoginService.java
=> 🔀 :: (#332) 어드민 토큰 role/"admin" -> enum값으로 변경

src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/presentation/ScheduleController.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
=> 🔀 :: (#334) url 규칙 통일시키기

src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserLoginService.java
=> 🔀 :: (#339) 로그인 예외 처리

src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/request/ChangeGraduationInformationRequest.java
=> 🔀 :: (#341) 유저 정보 변경 학번 검증

src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/exception/InvalidGraduateAtException.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeTypeService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
=> 🔀 :: (#344) 전형 구분 선택 시 졸업일 날짜 제한

src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/AuthCode.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/types/Action.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/exception/UnVerifiedAuthCodeException.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendEmailAuthCodeService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendPasswordAuthCodeService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserSignupService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
=> 🔀 :: (#338) 비밀번호 변경 인증 번호 발송 Api 수정

src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java
=> 🔀 :: (#346) 인증 번호 발송 Api에서 ttl 설정 수정

src/main/resources/application.yml
=> 🔀 :: (#350) show-sql option으로 변경

src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/request/ChangeTypeRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeTypeService.java
=> 🔀 :: (#348) 졸업자, 검정고시 졸업연도 입력 오류 400

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java
=> 🔀 :: (#336) 지원자 목록 엑셀

.github/CODEOWNERS
=> 🔀 :: (#351) Code Owners 추가

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/GetApplicantsRequest.java
이럴 때 값이 null로 넘어오지 않는데 숫자로 바꿀수도 없어서 400 오류가 발생한 것 같음
아예 없거나 값이 숫자인 경우엔 200
close #359
=> 🔀 :: (#359) 지원자 목록 QueryString 400 오류

src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/request/ChangeInformationRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
=> 🔀 :: (#362) User Sex NPE

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java
=> 🔀 :: (#364) 엑셀 값 OOB

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/response/ApplicantDetailsResponse.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantDetailsService.java
=> 🔀 :: (#366) 지원자 세부 정보 Response 수정

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java
=> 🔀 :: (#369) 지원자 목록 엑셀 '공란' -> '-'

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java
close #370 
""일 때 "x"를 출력해야 하는데 그 반대라서 값이 잘못 나왔었음.
"x"와 실제 DB에 저장된 "X"가 비슷하여 헷갈릴 수 있을 것 같아서 빈 칸은 "-"로 통일하였음.
=> 🔀 :: (#370) 지원자 목록 엑셀 성적 출력 버그 수정 및 'x' -> '-'

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantDetailsService.java
=> 🔀 :: (#374) 지원자 정보 가져오기 NPE 해결

src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/AuthCode.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendEmailAuthCodeService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendPasswordAuthCodeService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/ses/SESUtil.java
=> 🔀 :: (#368) 비밀번호 재설정 이메일 템플릿 설정

src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/AuthCodeLimit.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/types/Action.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendEmailAuthCodeService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendPasswordAuthCodeService.java
=> 🔀 :: (#377) 이메일 전송 안됨

src/main/resources/templates/introduction.html
=> 🔀 :: (#386) 빈칸 포함 1,600자 이내 추가 & 기타 에러 수정

src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserSignupService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/security/jwt/JwtTokenProvider.java
=> 🔀 :: (#392) 토큰 버그

src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/ApplicationPdfGenerator.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/TemplateFileName.java
=> 🔀 :: (#390) PDF 설정

src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/ApplicationCase.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/GraduationCase.java
=> 🔀 :: (#383) 봉사시간 수정

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/GetApplicantsRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/response/ApplicantsResponse.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantsService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/request/ChangeTypeRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/response/QueryTypeResponse.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
close #400 
* user 테이블에 is_out_of_headcount 추가
* 전형 구분 선택, 전형 구분 조회, 지원자 목록 수정
=> 🔀 :: (#400) head count 오류 해결 및 칼럼 추가

src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserRepository.java
=> 🔀 :: (#402) 파라미터가 9개인데 ?10을 호출해서 발생한 500 에러

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantsService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserRepository.java
=> 🔀 ::	(#403) null이라면 query 조건 패스

src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/security/auth/AuthDetailsService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/security/jwt/JwtTokenProvider.java
=> 🔀 :: (#405) 유저 role 오류 수정 및 수정사항 반영

build.gradle, src/main/java/kr/hs/entrydsm/rollsroyce/global/config/QuerydslConfig.java
=> 🔀 :: (#407) Querydsl 설정

build.gradle, src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/GetApplicantsRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantsService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/ScoreCustomRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/ScoreCustomRepositoryImpl.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/ScoreRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserCustomRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserCustomRepositoryImpl.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/vo/ApplicantVo.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java, src/main/resources/application.yml
close #409 
* 어드민 엑셀 출력 쪽은 쿼리를 최대한 줄일 수 있도록 리팩토링 하는 것이 좋을 것 같음. (기능 상 문제는 없음)
=> 🔀 :: (#409) querydsl 적용

src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserCustomRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserCustomRepositoryImpl.java
=> 🔀 :: (#415) limit, offset, orderBy 설정 + pageable 변수명 통일

src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserCustomRepositoryImpl.java
=> 🔀 :: (#418) in절로 수정

.github/CODEOWNERS, src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/GetApplicantsRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserCustomRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserCustomRepositoryImpl.java
=> 🔀 :: (#424) 변수명 수정

src/main/java/kr/hs/entrydsm/rollsroyce/global/security/WebConfig.java, src/main/resources/application.yml
=> 🔀 :: (#426) CORS Origins 수정

src/main/java/kr/hs/entrydsm/rollsroyce/global/security/WebConfig.java, src/main/resources/application.yml
=> 🔀 :: (#426) CORS Origin 설정

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/ExcelController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/excel/NewApplicantInformation.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/NewApplicantsExcelService.java
글자 굵기, 가운데정렬 같은건 시간안에 못할거 같아서 임시로 이것만
close #431
=> 🔀 :: (#431) 엑셀생성 new

src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/response/StatusResponse.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserStatusService.java
=> 🔀 :: (#437) educationalStatus 필드 추가

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/QueryStaticsCountService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/entryinfo/domain/EntryInfo.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/entryinfo/domain/repository/EntryInfoRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/status/domain/facade/StatusFacade.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/status/domain/repository/StatusRepository.java
=> 🔀 :: 오류 해결

src/main/java/kr/hs/entrydsm/rollsroyce/domain/entryinfo/domain/EntryInfo.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/entryinfo/domain/repository/EntryInfoRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/entryinfo/exception/EntryInfoAlreadyExistsException.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/entryinfo/service/CancelEntryService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/entryinfo/service/CreateEntryService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/reserve/ReserveController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java, src/main/resources/application.yml
=> 🔀 :: 지원정보 관련 API 구현

src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/domain/Qna.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/domain/repository/QnaRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/QnaController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/dto/request/CreateQnaRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/CreateQnaService.java
=> 🔀 :: Q&A 생성 API 구현

src/main/resources/application.yml
=> 🔀 :: (#459) ddl auto update -> create로 변경

src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/domain/Qna.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/exception/NotModifyQnaException.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/exception/QnaNotFoundException.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/facade/QnaFacade.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/QnaController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/dto/request/UpdateQnaRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/UpdateQnaService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
=> 🔀 :: (#455) 질문 수정 API 구현

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/domain/Reply.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/domain/repository/ReplyRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/AdminController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/CreateReplyRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/CreateReplyService.java
=> 🔀 :: (#462) 답변 생성 API 구현

src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/QnaController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/dto/request/CreateQnaRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/dto/request/UpdateQnaRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/CreateQnaService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/UpdateQnaService.java
=> 🔀 :: (#475) 오타 수정

src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/dto/request/CreateQnaRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/CreateQnaService.java
=> 🔀 :: (#477) isReplied 삭제

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/domain/Reply.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/domain/Qna.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/entity/BaseTimeEntity.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/entity/QnaTimeEntity.java
=> 🔀 :: (#479) BaseTimeEntity 설정

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/domain/Reply.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/domain/Qna.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/request/PasswordRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/ChangePasswordService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/entity/QnaTimeEntity.java
=> 🔀 :: (#483) 비밀번호 변경 API 구현

src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/UploadPhotoService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/s3/S3Util.java
=> 🔀 :: (#488) S3에 폴더 경로 추가

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/CreateReplyService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/domain/Notice.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/domain/Qna.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
=> 🔀 :: (#496) 코드 전체적인 사소한 수정

src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/domain/Qna.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/domain/repository/QnaRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/QnaController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/dto/response/QueryQnaResponse.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/QueryQnaService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
=> 🔀 :: (#493) 질문 전체 조회 API 구현

src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/domain/Qna.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/QueryQnaService.java
=> 🔀 :: (#500) 데이터 반환 에러 해결

src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/domain/Notice.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/presentation/NoticeController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/presentation/dto/request/UpdateNoticeRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/service/UpdateNoticeService.java
=> 🔀 :: (#492) 공지사항 수정 API 구현

.github/workflows/CD.yml
=> 🔀 :: (#503) gradle build action으로 변경

src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/domain/Screen.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/domain/repository/ScreenRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/presentation/ScreenController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/presentation/dto/request/CreateScreenRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/service/CreateScreenService.java
=> 🔀 :: (#490) 전형요강 생성 API 구현

src/main/java/kr/hs/entrydsm/rollsroyce/domain/entryinfo/service/CreateEntryInfoService.java
=> 🔀 :: (#509) 지원정보 생성 시 status 생성

src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/UploadPhotoService.java
=> 🔀 :: (#506) Access Denied Error 해결

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/domain/repository/ReplyRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/dto/response/QueryDetailsQnaResponse.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/QueryDetailsQnaService.java
=> 🔀 :: (#524) response 값 수정

src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/domain/repository/NoticeRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/presentation/NoticeController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/presentation/dto/request/CreateNoticeRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/presentation/dto/response/QueryNoticeResponse.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/service/QueryNoticeService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
=> 🔀 :: (#513) 공지사항 전체조회 API 구현

src/main/java/kr/hs/entrydsm/rollsroyce/domain/pass/exception/AdmissionUnavailableException.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/pass/presentation/IsPassedController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/pass/presentation/dto/response/QueryIsFirstRoundPassResponse.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/pass/presentation/dto/response/QueryIsSecondRoundPassResponse.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/pass/service/QueryIsFirstRoundPassService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/pass/service/QueryIsSecondRoundPassService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/status/domain/Status.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
=> 🔀 :: (#526) 1, 2차 합격 여부 조회 API

src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/domain/repository/QnaRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/facade/QnaFacade.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/QnaController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/QueryMyQnaService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
=> 🔀 :: (#515) 내 질문 조회 API 구현

src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/domain/BannerLink.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/domain/repository/BannerLinkRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/presentation/BannerLinkController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/service/UploadBannerLinkService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/exception/BannerLinkNotFoundException.java
=> 🔀 :: (#536) 배너링크 업로드 API

src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/domain/BannerLink.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/presentation/BannerLinkController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/service/CreateBannerLinkService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
=> 🔀 :: (#545) 배너 생성 API 구현

src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/exception/NoticeNotFoundException.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/presentation/NoticeController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/service/DeleteNoticeService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
=> 🔀 :: (#547) 공지사항 삭제 API 구현

src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/domain/Screen.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/exception/ScreenNotFoundException.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/presentation/ScreenController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/presentation/dto/request/UpdateScreenRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/service/UpdateScreenService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
=> 🔀 :: (#531) 전형요강 수정 API 구현

build.gradle, src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/domain/Faq.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/domain/repository/FaqRepository.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/domain/type/FaqType.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/exception/FaqNotFoundException.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/presentation/FaqController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/presentation/dto/request/CreateFaqRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/presentation/dto/request/UpdateFaqRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/presentation/dto/response/QueryFaqInfoResponse.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/presentation/dto/response/QueryFaqResponse.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/service/CreateFaqService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/service/DeleteFaqService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/service/QueryFaqInfoService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/service/QueryFaqListByTypeService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/service/QueryFaqListService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/service/UpdateFaqService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
=> 🔀 :: (529) Faq CRUD API 

src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/presentation/BannerLinkController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/presentation/dto/response/QueryBannerLinkListResponse.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/service/QueryBannerLinkListService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
=> 🔀 :: (#543) 배너 조회 API 구현

src/main/java/kr/hs/entrydsm/rollsroyce/global/security/WebConfig.java, src/main/resources/application.yml
=> 🔀 :: (#506) 도메인 추가

src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/presentation/NoticeController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/service/UploadNoticeImageService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/s3/S3Util.java
=> 🔀 :: (#553) 공지사항 사진 업로드 api 구현

src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/request/ChangeInformationRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/response/QueryUserInfoResponse.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeInformationService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/QueryUserInfoService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/entryinfo/domain/EntryInfo.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/entryinfo/service/CreateEntryInfoService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/request/SignupRequest.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserSignupService.java
=> 🔀 :: (#574) isStudent 추가

.github/workflows/CD.yml
=> 🔀 :: (#581) CD 수정

src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/PdfDataConverter.java
=> 🔀 :: (#576) isStudent에 따라 코드 변경

src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/ExcelController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/PrintApplicantsService.java
=> 🔀 :: (#585) 지원자 목록 API 엑셀 출력으로 재변경

build.gradle, src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/facade/ScheduleFacade.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/service/GetSchedulesService.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/service/UpdateSchedulesService.java, src/main/java/kr/hs/entrydsm/rollsroyce/global/config/CacheConfig.java
=> 🔀 :: (#577) Schedule 캐싱

src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/presentation/NoticeController.java, src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/service/QueryNoticeListByTypeService.java
=> 🔀 :: (#588) 공지사항 조회시 QueryParam으로 변경
